/**
 * Build-time prerenderer.
 *
 * Runs after `vite build`. Serves dist/ locally, renders every known route in
 * headless Chrome, and writes the fully rendered HTML (title, meta, canonical,
 * OG tags, JSON-LD, body content) to dist/<route>/index.html so crawlers get
 * real HTML without executing JavaScript.
 *
 * Also generates dist/_redirects: explicit 200 rules for every real route,
 * 301s for legacy /blog URLs, and a final wildcard that returns a true 404.
 */
import { createServer } from 'node:http';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, extname, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, '..', 'dist');
const SRC = join(ROOT, '..', 'src');

/* ── 1. Collect routes ─────────────────────────────────────────── */

function extractSlugs(file) {
  if (!existsSync(file)) return [];
  const source = readFileSync(file, 'utf8');
  return [...source.matchAll(/slug:\s*'([^']+)'/g)].map(m => m[1]);
}

const staticRoutes = [
  '/',
  '/about',
  '/features',
  '/contact',
  '/pricing',
  '/resources',
  '/resources/blog',
  '/resources/case-studies',
  '/privacy-policy',
  '/terms-of-service',
];

const routes = [
  ...staticRoutes,
  ...extractSlugs(join(SRC, 'pages', 'product', 'ProductPage.tsx')).map(s => `/product/${s}`),
  ...extractSlugs(join(SRC, 'pages', 'industries', 'IndustryPage.tsx')).map(s => `/industries/${s}`),
  ...extractSlugs(join(SRC, 'data', 'blogs.ts')).map(s => `/resources/blog/${s}`),
  ...extractSlugs(join(SRC, 'data', 'caseStudies.ts')).map(s => `/resources/case-studies/${s}`),
  ...extractSlugs(join(SRC, 'data', 'comparisons.ts')).map(s => `/compare/${s}`),
];

const NOT_FOUND_ROUTE = '/__404__';

/* ── 2. Tiny static file server with SPA fallback ─────────────── */

const MIME = {
  '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css',
  '.json': 'application/json', '.png': 'image/png', '.webp': 'image/webp',
  '.svg': 'image/svg+xml', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.xml': 'application/xml', '.txt': 'text/plain', '.ico': 'image/x-icon',
  '.woff': 'font/woff', '.woff2': 'font/woff2',
};

const server = createServer((req, res) => {
  const urlPath = decodeURIComponent(new URL(req.url, 'http://localhost').pathname);
  let filePath = join(DIST, urlPath);
  if (!extname(filePath)) filePath = join(DIST, 'index.html');
  try {
    const body = readFileSync(existsSync(filePath) ? filePath : join(DIST, 'index.html'));
    res.writeHead(200, { 'Content-Type': MIME[extname(filePath)] ?? 'application/octet-stream' });
    res.end(body);
  } catch {
    res.writeHead(404);
    res.end('not found');
  }
});

/* ── 3. Render every route, snapshot HTML ──────────────────────── */

function outputPathFor(route) {
  if (route === NOT_FOUND_ROUTE) return join(DIST, '404.html');
  if (route === '/') return join(DIST, 'index.html');
  return join(DIST, ...route.split('/').filter(Boolean), 'index.html');
}

const port = await new Promise(resolve => {
  server.listen(0, '127.0.0.1', () => resolve(server.address().port));
});

const browser = await puppeteer.launch({ headless: true });
const page = await browser.newPage();

// Keep snapshots deterministic and fast: allow only same-origin requests, so
// third-party widgets (live chat, fonts, analytics) never get baked into the HTML.
await page.setRequestInterception(true);
page.on('request', req => {
  req.url().startsWith(`http://127.0.0.1:${port}`) ? req.continue() : req.abort();
});

let failures = 0;
for (const route of [...routes, NOT_FOUND_ROUTE]) {
  try {
    await page.goto(`http://127.0.0.1:${port}${route}`, { waitUntil: 'networkidle0', timeout: 60_000 });
    // Give helmet/framer a beat to settle after the last network response.
    await new Promise(r => setTimeout(r, 350));
    const html = await page.content();
    const outFile = outputPathFor(route);
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, html);
    const title = (html.match(/<title[^>]*>([^<]*)<\/title>/) ?? [])[1] ?? '(no title)';
    console.log(`✓ ${route}  →  "${title.slice(0, 70)}"`);
  } catch (err) {
    failures++;
    console.error(`✗ ${route}: ${err.message}`);
  }
}

await browser.close();
server.close();

/* ── 4. Generate _redirects ────────────────────────────────────── */

const redirects = [
  '# Generated by scripts/prerender.mjs — do not edit by hand',
  '',
  '# Legacy short blog URLs → canonical location',
  '/blog              /resources/blog              301',
  '/blog/*            /resources/blog/:splat       301',
  '',
  '# Explicit rules for every real route (files are prerendered; these are a safety net)',
  ...routes.map(r => `${r.padEnd(50)} /index.html 200`.replace(' /index.html 200', '   /index.html   200')),
  '',
  '# Everything else is a real 404',
  '/*   /404.html   404',
].join('\n');

writeFileSync(join(DIST, '_redirects'), redirects);
console.log(`\nPrerendered ${routes.length + 1 - failures}/${routes.length + 1} pages, wrote _redirects (${routes.length} explicit routes).`);
if (failures > 0) process.exit(1);
